# StudyVerse Render Blueprint - Fixed for Complete Deployment
# AI-Powered Learning That Grows With You

services:
  # Backend API Service - MUST deploy first
  - type: web
    name: studyverse-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m gunicorn main:app --bind 0.0.0.0:$PORT
    plan: starter
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false  # User will add this manually
      - key: OPENAI_API_BASE
        value: https://api.openai.com/v1
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /api/health
    scaling:
      minInstances: 1
      maxInstances: 3

  # Frontend Static Site - Deploys after backend
  - type: web
    name: studyverse-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    plan: starter
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: studyverse-backend
          property: host
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff

# CRITICAL DEPLOYMENT NOTES:
# 1. Backend service MUST be deployed first to generate API URL
# 2. Frontend will automatically receive backend URL via VITE_API_URL
# 3. Both services must be in same Blueprint deployment
# 4. User MUST add OPENAI_API_KEY after deployment for AI features
# 5. Health check at /api/health verifies backend is running

# Environment Variables Required:
# - OPENAI_API_KEY: Your OpenAI API key (add manually after deployment)
# - SECRET_KEY: Auto-generated by Render for JWT security
# - VITE_API_URL: Auto-generated from backend service URL

